export const Data = [
  {
    id: Math.random(),
    title: "وجبه فطار",
    discription: "وجبه الفطار",
    price: "50 جنيه",
    category: "فطار",
    imageUrl: "download (1).jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه غداء",
    discription: "وجبه الغداء",
    price: "جنيه 90",
    category: "غداء",
    imageUrl: "OIP (2).jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    discription: "وجبه العشاء",
    price: "جنيه 70 ",
    category: "عشاء",
    imageUrl: "OIP.jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه فطار",
    discription: "وجبه الفطار",
    price: "30 جنيه",
    category: "فطار",
    imageUrl: "th.jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه فطار",
    discription: "وجبه الفطار",
    price: "55 جنيه",
    category: "فطار",
    imageUrl: "OIP (1).jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه عشاء",
    discription: "وجبه العشاء",
    price: "جنيه 40 ",
    category: "عشاء",
    imageUrl: "download.jpeg",
  },
  {
    id: Math.random(),
    title: "وجبه غداء",
    discription: "وجبه الغداء",
    price: "جنيه 30",
    category: "غداء",
    imageUrl: "download (2).jpeg",
  },
];